name: Deploy Mion to VPS
on:
  push:
    branches:
      - main

          
jobs:
  deploy:
    name: deploy to prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    
    - name: bun install and build
      run: |
        ssh -i ~/.ssh/id_ed25519  ${{secrets.LOGIN}} << 'EOF'
          cd ~/mion-bot
          git pull origin main
          bun install
          pm2 reload mion-bot
        EOF


