name: Deploy Mion to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy to prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: bun install and build
      run: |
        ssh -o StrictHostKeyChecking=no  ${{secrets.LOGIN}} << 'EOF'
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          cd ~/mion-bot
          git pull origin main
          bun install
          bun pm2 reload mion-bot
        EOF